import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Preguntas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={raleway.className}>{children}</body>
      </Providers>
    </html>
  );
}
